### ISSUE TITLE
Installing Pipeline CLI works, but SyntaxError when executing "pipeline version"

### ISSUE THREAD

**Issue by kaiwaehner** [PipelineAI/pipeline#277]
I installed Pipeline CLI successfully on my Mac in a new conda environment as described here: 
https://github.com/PipelineAI/pipeline/tree/master/docs/quickstart/community

Here are my steps:

python => Shows: Python 3.7.0 (default, Jun 28 2018, 07:39:16)
conda create -n PipelineAI
conda create -n PipelineAI
conda install -n PipelineAI pip
which pip => Shows: /Users/kai.waehner/anaconda2/envs/PipelineAI/bin/pip
pip install cli-pipeline==1.5.206 --default-timeout=120 --ignore-installed --no-cache --upgrade

=> This successfully installs cli-pipeline. But if I execute "pipeline" or "pipeline version", it throws the following error:

`kai.waehner@Kais-MacBook-12:~/anaconda2/envs/PipelineAI/bin|
⇒  ./pipeline version
Traceback (most recent call last):
  File "./pipeline", line 7, in <module>
    from cli_pipeline.cli_pipeline import _main
  File "/Users/kai.waehner/anaconda2/envs/PipelineAI/lib/python3.7/site-packages/cli_pipeline/cli_pipeline.py", line 25, in <module>
    import kubernetes.client as _kubeclient
  File "/Users/kai.waehner/anaconda2/envs/PipelineAI/lib/python3.7/site-packages/kubernetes/__init__.py", line 19, in <module>
    import kubernetes.client
  File "/Users/kai.waehner/anaconda2/envs/PipelineAI/lib/python3.7/site-packages/kubernetes/client/__init__.py", line 540, in <module>
    from .apis.admissionregistration_api import AdmissionregistrationApi
  File "/Users/kai.waehner/anaconda2/envs/PipelineAI/lib/python3.7/site-packages/kubernetes/client/apis/__init__.py", line 4, in <module>
    from .admissionregistration_api import AdmissionregistrationApi
  File "/Users/kai.waehner/anaconda2/envs/PipelineAI/lib/python3.7/site-packages/kubernetes/client/apis/admissionregistration_api.py", line 120
    async=params.get('async'),
        ^
SyntaxError: invalid syntax`

Any hints?

Kai

**Comment by cfregly** [comment]
hey @kaiwaehner!

thanks for letting us know.

it might be a python 3.7 thing.  we're taking a look now.

**Comment by cfregly** [comment]
we'll need to upgrade the kubernetes-client python dependency for python 3.7 per https://github.com/kubernetes-client/python/blob/master/CHANGELOG.md

![image](https://user-images.githubusercontent.com/1438064/44180750-2c314880-a0cc-11e8-8fad-cf828592e815.png)

**Comment by cfregly** [comment]
1.5.207 is now avaiilable with kube-client 7.0+
